-- ===============================================================
-- Author: Nigina Irgasheva
-- Date: 2025-10-14
-- Topic: CTE
-- Task: 
-- Input Tables: orders
-- Output Columns: customer_id, total_amount
-- ===============================================================
